# Generated by Django 6.0.2 on 2026-03-05 06:51

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('small_testcases', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', markdownx.models.MarkdownxField()),
                ('time_limit', models.FloatField(default=1.0)),
                ('memory_limit', models.IntegerField(default=256000)),
                ('difficulty', models.IntegerField(default=800)),
                ('problem_code', models.CharField(default='', max_length=200)),
                ('show_test', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='problems', to='judge.category')),
                ('test_cases', models.ManyToManyField(to='judge.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='profile_pics')),
                ('bio', markdownx.models.MarkdownxField(blank=True)),
                ('rating', models.IntegerField(default=1500)),
                ('github_url', models.URLField(blank=True)),
                ('solved_problems', models.ManyToManyField(blank=True, to='judge.problem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_code', models.TextField(null=True)),
                ('code', models.TextField(null=True)),
                ('language', models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('asm', 'Assembly (NASM)')], max_length=10)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('JG', 'Judging'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('CE', 'Compile Error')], default='PD', max_length=3)),
                ('result_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
