# Generated by Django 6.0.2 on 2026-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_cases',
        ),
        migrations.DeleteModel(
            name='Testcase',
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
