# Generated by Django 6.0.2 on 2026-03-05 12:30

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_remove_problem_test_cases_delete_testcase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', markdownx.models.MarkdownxField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('problem', models.ManyToManyField(to='judge.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', markdownx.models.MarkdownxField()),
                ('user', models.ManyToManyField(to='judge.profile')),
            ],
        ),
    ]
