# Generated by Django 6.0.2 on 2026-03-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_contests_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contests',
            new_name='Contest',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
