# Generated by Django 6.0.2 on 2026-03-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_rename_contests_contest_rename_groups_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='judge.group'),
        ),
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.contest'),
        ),
    ]
