# Generated by Django 6.0.2 on 2026-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_contest_group_submission_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_for_contest',
            field=models.BooleanField(default=False),
        ),
    ]
