# Generated by Django 6.0.2 on 2026-03-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_problem_is_for_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='judge.group'),
        ),
    ]
