# Generated by Django 6.0.2 on 2026-03-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_alter_contest_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
