# Generated by Django 6.0.2 on 2026-03-05 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_submission_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='participants',
        ),
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='contests_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
