# Generated by Django 6.0.2 on 2026-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_rename_blogs_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='badge_pics')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='judging_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
