# Generated by Django 6.0.2 on 2026-03-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0014_judgenode_alter_profile_user_submission_judge_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgenode',
            name='status',
            field=models.CharField(choices=[('ON', 'online'), ('OF', 'offline'), ('RS', 'restarting')], default='OF', max_length=3),
        ),
    ]
