# Generated by Django 6.0.2 on 2026-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0015_judgenode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgenode',
            name='supported_languages',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
