# Generated by Django 6.0.2 on 2026-03-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0016_judgenode_supported_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgenode',
            name='languages_matrix',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='judgenode',
            name='supported_languages',
            field=models.CharField(editable=False, null=True),
        ),
    ]
